name: Challenge1

on: [push, workflow_dispatch]

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
    - name: date1
      run: now="$(date)" printf "Current date and time %s\n" "$now"

  job2:
    name: job2
    runs-on: windows-latest
    steps:
    - name: date2
      run: Get-Date -DisplayHint Date

  job3:
    name: job3
    runs-on: macos-latest
    steps:
    - name: date3
      run: now="$(date)"
            printf "Current date and time %s\n" "$now"

  job4:
    name: job4
    runs-on: macos-latest
    needs: [job1, job2, job3]
    steps:
    - name: date4
      run: now="$(date)"
            printf "Current date and time %s\n" "$now"
