name: first

on: 
  push:
      branches: ##or use branches-ignore; tags/tag-ignore
        - develop
        - master
  pull_request:
      branches:
        - develop
        - master
    

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: env | sort
  job2:
    name: second job
    runs-on: windows-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: "Get-ChildItem Env: | Sort-Object Name"
    

#### Action notes: Can call action from public repo OR the same repo as the action is in OR a docker image registry e.g. dockerhub docker://hello-world:latest
#### run: a single command on the default shell (bash or powershell)
#### on: can use regex to identify branches with particular patterns
### Action limitations: 20-120 concurrent jobs; 1000 github API requests/hour
### Action logs max 64 kb

