name: Hello World
on: [push] ###This can be many kinds of webhook, like branch,issue creation, member joining/leaving
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - run: echo Hello, world!
